name: ResourceGenerator
version: 1.1
main: com.noasaba.resourceGenerator.ResourceGenerator
api-version: 1.21
depend:
  - Multiverse-Core
  - Multiverse-NetherPortals

commands:
  resource:
    description: 資源ワールドを作成し、設定コマンドを適用する
    usage: /resource create [-s <seed>]
    permission: resourcegenerator.admin

permissions:
  resourcegenerator.admin:
    description: 資源ワールド管理権限
    default: op
